spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: rootsu
    url: jdbc:mysql://localhost/sell?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell
wechat:
  mpAppId: wxd898fcb01713c658
  mpAppSecret: 47ccc303338cee6e62894fxxxxxxxxxxx
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://sell.natapp4.cc/sell/pay/notify
Spring:
  resources:
    static-locations: classpath:/
#projectUrl:
 # sell: http://127.0.0.1:8080
