spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: rootsu
    url: jdbc:mysql://localhost/sell?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  jpa:
    show-sql: true
  redis:
    host: 127.0.0.1
    port: 6379
server:
  servlet:
    context-path: /sell
wechat:
  mpAppId: wx2fee82e63a973df5
  mpAppSecret: c63e4b131d36451d733fbbf48f80018d
  openAppId: wxd898fcb01713c658
  openAppSecret: 47ccc303338cee6e62894fxxxxxxxxxxx
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://godsu.mynatapp.cc/sell/pay/notify
projecturl:
  wechatMpAuthorize: http://godsu.mynatapp.cc
  wechatOpenAuthorize: http://godsu.mynatapp.cc
  sell: http://godsu.mynatapp.cc
