spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: su1006
    url: jdbc:mysql://localhost/sell?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell

